FROM legalthings/apache-php71
  
RUN apt-get install -y git netbase

ADD build/ /build
WORKDIR /build
RUN composer install --no-dev

ADD bin/ /tmp
WORKDIR /tmp

RUN ./ioncube_encoder.sh -71 --activate 
RUN ./ioncube_encoder.sh -71 /build -o /app --keep-comments --replace-target

# Cleanup
RUN rm -rf /tmp/* && rm -rf /build

WORKDIR /app

ENV APACHE_DOCUMENT_ROOT /var/www/html/www
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf

